### ISSUE TITLE
Error when exchanging active and inactive (down) DNS-Records

### ISSUE THREAD

**Issue by 8-bit-fox** [Myra-Security-GmbH/terraform-provider-myrasec#115]
Hi,

I have a problem using the terraform-provider which seems like a race-condition on Myra's side.
I have two DNS-Records, where one is active and the other one is down. Then, I want to get the second on up and the first one down. A plan looks like

```terraform
  # myrasec_dns_record.site1 will be updated in-place
  ~ resource "myrasec_dns_record" "site1" {
        id                = "1234567"
        name              = "site.example.com"
        # (13 unchanged attributes hidden)

      ~ upstream_options {
          ~ backup       = true -> false
          ~ down         = true -> false
            # (6 unchanged attributes hidden)
        }
    }

  # myrasec_dns_record.site2 will be updated in-place
  ~ resource "myrasec_dns_record" "site2" {
        id                = "2345678"
        name              = "site.example.com"
        # (13 unchanged attributes hidden)

      - timeouts {}

      ~ upstream_options {
          ~ backup       = false -> true
          ~ down         = false -> true
            # (6 unchanged attributes hidden)
        }
    }
```
During the apply-phase, Terraform throws an error from the API:
```
myrasec_dns_record.site1: Modifying... [id=1234567]
myrasec_dns_record.site2: Modifying... [id=2345678]
myrasec_dns_record.site2: Modifications complete after 1s [id=2345678]
╷
│ Error: Error updating DNS record
│ 
│   with myrasec_dns_record.site1,
│   on dns_record.tf.json line 4820, in resource.myrasec_dns_record[123].site1:
│ 4820:         }
│ 
│ 2023-06-02T11:14:28.113662564Z: Bad Request (400):
│ upstreamOptions: The DNS record can not be updated because there would be
│ no active upstream left.
│ 
╵
```

My suspicion is that it tries to remove on record from the load-balancing before the other one was added, which is not handled gracefully by the back-end. This is emphasized by the fact that the appearance of the error seems to be sensitive to the order in which the records are updated.

How would I overcome the issue? Is there an option to keep the secondary site in the LB up but set the weight to infinity such that it's never targeted? Or am I using the objects entirely wrong?

Best regards

**Comment by smashi** [comment]
Hi @8-bit-fox ,
i think the only way to solve this issue, is to tell terraform that the resources depends on each other.

on the resource you want to set the values to true, you have to set the `depends_on` attribute:
```
resource "myrasec_dns_record" "site2" {
  ...
  depends_on = [myrasec_dns_record.site1]
  upstream_options {
    backup = true
  }
}
```

BR Tim

**Comment by 8-bit-fox** [comment]
Hi @smashi ,

this is unfortunate as the switch of load-balancing back to the original site would require inverting the dependency. How would one deal with that? How does the `load-balancing weight` option work, when the value is set to zero/minus one?

Best regards
Sebastian

**Comment by 8-bit-fox** [comment]
Hi @smashi,

we solved it by dynamically setting the `depends_on` attribute. Surely not the nicest solution, but it works.

Best regards,
Sebastian
