### ISSUE TITLE
Datasource: Outgoing Myra IPs

### ISSUE THREAD

**Issue by bebehei** [Myra-Security-GmbH/terraform-provider-myrasec#12]
We've got a list of specified IPs, which are in our use. We use these IPs to connect to our customers.

This is currently an API call in our App to query these IP-Ranges. It would be nice, if we could create a datasource for it. So customers can automatically connect it with their AWS/GCP/... infrastructure. Without any manual change, the IP range could be deployed there.

It would be nice, if the following example would work out and

```terraform
data "myrasec_outgoing_ips" "myraips_6" {
    filter {
        type = "ipv6"
    }
}

data "myrasec_outgoing_ips" "myraips_4" {
    filter {
        type = "ipv4"
    }
}

data "myrasec_outgoing_ips" "myraips_all" {
}


output "myraips_v6" {
    value = data.myrasec_outgoing_ips.myraips_6.ip_list
}

output "myraips_v4" {
    value = data.myrasec_outgoing_ips.myraips_4.ip_list
}

output "myraips_all" {
    value = data.myrasec_outgoing_ips.myraips_all.ip_list
}
```

And the output values something like this:

```
[bebe:/tmp/test-terraform] % terraform apply
[...]

Outputs:

myraips_v6 = [
  "fefe::1/128",
  ...
]

myraips_v4 = [
  "1.2.3.4/24",
  ...
]

myraips_all = [
  "1.2.3.4/24",
  "fefe::1/128",
  ...
]
```

This would be the basis, that our customers can easily reference our IPs and add them to their Firewall Template

**Comment by robertwe** [comment]
@nj-b lets put some priority on this please

**Comment by xellio** [comment]
@bebehei - v1.20.0 of the provider contains a basic implementation of a datasource for ip ranges. It does not yet contain filters for IPv4 or IPv6 addresses. I will update you as soon as this is implemented, too.

**Comment by xellio** [comment]
Version v1.48.0 of the provider now supports a `type` filter on IP ranges. 

You can specifiy the IP version type like this (for fetching only IPv4 IP ranges):
```
data "myrasec_ip_ranges" "ip_ranges" {
  filter {
    type = "ipv4"
  }
}
```
or like this for fetching only IPv6 IP ranges:
```
data "myrasec_ip_ranges" "ip_ranges" {
  filter {
    type = "ipv6"
  }
}
```

https://registry.terraform.io/providers/Myra-Security-GmbH/myrasec/latest/docs/data-sources/ip_ranges
