### ISSUE TITLE
data source myrasec_dns_records display only 1st page

### ISSUE THREAD

**Issue by lejardindeden** [Myra-Security-GmbH/terraform-provider-myrasec#13]
Hi,

I am Julien working along with Dmitry. I am facing issues to retrieve data from your provider.

When trying to access data sources, in my case myrasec_dns_records, I am able to fetch records from the first page only, I tried to increase the filter with "name" or "match" but the filter is still done only on the first page available on the Myracloud UI.

How could we please access other pages ?

**Comment by robertwe** [comment]
Hi @lejardindeden many thx for reporting the issue.
Could you please share with me what version of the TF and provider itself you are using?

**Comment by xellio** [comment]
I think the problem on this is the API implementation (https://github.com/Myra-Security-GmbH/myrasec-go). Right now, the ListDNSRecords action shows always the first page.

See:
https://github.com/Myra-Security-GmbH/myrasec-go/blob/master/methods.go#L44
https://github.com/Myra-Security-GmbH/myrasec-go/blob/master/dnsrecord.go#L52

This happens on other actions, too (for example https://github.com/Myra-Security-GmbH/myrasec-go/blob/master/ratelimit.go#L44)

We should allow passing the page parameter to the API action.

**Comment by robertwe** [comment]
I think passing an extra parameter like page number or even better total page number (instead of "please display page X" something like "please display last Y pages" - what probably is more useful).

**Comment by robertwe** [comment]
PRs are ready:
 - https://github.com/Myra-Security-GmbH/terraform-provider-myrasec/pull/15
 - https://github.com/Myra-Security-GmbH/myrasec-go/pull/7
 
That should sole the problem with list of the DNS records (previously it was truncated to 50 entries)

**Comment by robertwe** [comment]
@lejardindeden could you please check it once again please with the latest release ? `v1.17.4`

**Comment by robertwe** [comment]
@nj-b Im closing this issue. @lejardindeden in case you will face this issue again please create a new issue and link it to this one.
