### ISSUE TITLE
unable to import any myrasec_redirect resources

### ISSUE THREAD

**Issue by lejardindeden** [Myra-Security-GmbH/terraform-provider-myrasec#17]
Hey, 

Thank you for your work done in this repo, we are starting to implement more and more feature with your provider. 

The next resource we want to set via terraform is myrasec_redirect.
We have existing redirects and so we want to import them via terraform BUT

when trying:
` terraform import myrasec_redirect.test <redirect_ID>`
I am always getting the following error:
`Error: Error fetching redirects: EOF`

Similar issue for myrasec_dns_record:
`Error: Error fetching DNS records: EOF`

_Terraform: v1.0.3
Myracloud: v1.17.4_

PS: the matching_type field is not working, always set as Exact.

**Comment by xellio** [comment]
Sorry for the late response.
We updated our terraform provider. Please use the latest version (v1.18.0) and try importing your redirect(s) like:

```
terraform import myrasec_redirect.test example.com:1234
```

Please let me know if this works for you. 

We will check the issue with the matching_type, too. I will inform you as soon as we release a fix for this.

Thanks in advance!

**Comment by hakankpunkt** [comment]
Kannst du mich hier bitte rausnehmen?

-- 
Hakan Küçükyılmaz, +49 171 19 19 839

**Comment by SchlegelS0208** [comment]
> Sorry for the late response. We updated our terraform provider. Please use the latest version (v1.18.0) and try importing your redirect(s) like:
> 
> ```
> terraform import myrasec_redirect.test example.com:1234
> ```
> 
> Please let me know if this works for you.
> 
> We will check the issue with the matching_type, too. I will inform you as soon as we release a fix for this (#19).
> 
> Thanks in advance!

Works perfectly! 🥇  This bug is solved by v1.18.0 👍 
We had the same issue, but now it's working as expected, the resource gets imported successfully.

Thank you very much!

**Comment by lejardindeden** [comment]
Hi @xellio,

The import is indeed working! But when I want to see the details of the resource, I am only getting the id field, which is useless if I want to import a list of existing redirects in my state. Could we please get all fields from that resource instead of only id ?

Moreover, with v1.18.0, I am now seeing a new console error when applying changes (the changes applied properly):
`unexpected format of ID (<ID>), expected name:ID`

PS: Could we please add comment field which is missing.

Thank you!

**Comment by xellio** [comment]
Please update your settings to use the new 1.18.2 version of this provider. I fixed this issue.
