### ISSUE TITLE
myrasec_redirect created with  matching_type  = "prefix" has type "Exact" 

### ISSUE THREAD

**Issue by dshumsky** [Myra-Security-GmbH/terraform-provider-myrasec#19]
When I create redirect by
```
resource "myrasec_redirect" "some_name" {
  ....
  matching_type  = "prefix"
  ...
}
```

it has "Exact" type in Myracloud IU.

----

When `terraform plan` is called the second time it shows:
```
+ matching_type  = "prefix" # forces replacement
```

**Comment by xellio** [comment]
@robertwe Can you take a look at this issue?

**Comment by robertwe** [comment]
@xellio sure, will try to take a look at it today.

**Comment by robertwe** [comment]
@xellio okay I think I know what can cause it. I will try to release it at the end of this week (with the batch of other DNS release fixes).

**Comment by SchlegelS0208** [comment]
> @xellio okay I think I know what can cause it. I will try to release it at the end of this week (with the batch of other DNS release fixes).

Hi @robertwe ,
we experience the same issue as @dshumsky reported on August, 30.

Example:
`
  # myrasec_redirect.redirect_xyz_bratwurst must be replaced
-/+ resource "myrasec_redirect" "redirect_xyz_bratwurst" {
      ~ created        = "2021-12-20T13:07:49+01:00" -> (known after apply)
      ~ id             = "bratwurst.de:1164701" -> (known after apply)
      + matching_type  = "exact" # forces replacement
      ~ modified       = "2021-12-20T13:07:49+01:00" -> (known after apply)
      ~ redirect_id    = 1164701 -> (known after apply)
        # (6 unchanged attributes hidden)

      - timeouts {}
    }
`

Within MYRA UI the "matching_type" is set to "Exact" but the resource "myrasec_redirect" always tries to replace the resource definition, even with the right configuration in terraform.


I also encountered that the "data" block returns an empty "matching_type" for "myrasec_redirects":
`
Changes to Outputs:
  + redirects_xyz_bratwurst = {
      + filter    = [
          + {
              + search         = ""
              + subdomain_name = "xyz-bratwurst.de"
            },
        ]
      + id        = "1640608574"
      + redirects = [
          + {
              + created        = "2021-12-20T13:07:49+01:00"
              + destination    = "https://de.my-bockwurst.com/$1"
              + enabled        = true
              + id             = 1164701
              + matching_type  = ""
              + modified       = "2021-12-20T13:07:49+01:00"
              + sort           = 0
              + source         = "^/(.*)"
              + subdomain_name = "xyz-bratwurst.de."
              + type           = "permanent"
            },
        ]
      + timeouts  = null
    }
`

Could you take some action on this? :)

**Comment by xellio** [comment]
I will have a look on this issue and fix it. I will inform you as soon as we release a fix for this.

**Comment by xellio** [comment]
Please update your settings to use the new **1.18.2** version of this provider. I fixed this issue. Now it is possible to create redirects with matching_type = exact, prefix or suffix.
