### ISSUE TITLE
Redirects API is slow

### ISSUE THREAD

**Issue by dshumsky** [Myra-Security-GmbH/terraform-provider-myrasec#20]
Good morning,

When we have hundreds of redirects configured for subdomain the API becomes to be very slow. It takes around 30 seconds to create or delete Redirect.
We tried to use API v2, but it didn't help.
Here is the logs:

> 2021-09-14 08:11:18.269  DELETE /1000018/redirects/lidl.be/1107959
> 2021-09-14 08:12:13.389  Status code : 204 NO_CONTENT
> 
> 2021-09-14 08:12:13.392  DELETE /1000018/redirects/lidl.be/1107965
> 2021-09-14 08:13:07.520  Status code : 204 NO_CONTENT
> 
> 2021-09-14 08:13:07.523  DELETE /1000018/redirects/lidl.be/1107971
> 2021-09-14 08:14:01.902  Status code : 204 NO_CONTENT

Would it be possible to make it faster? Thanks

**Comment by xellio** [comment]
Good morning,

We will have a look at this with high prio! I will inform you about this as soon as we optimized/fixed the performance issues.

**Comment by xellio** [comment]
Hello @dshumsky
Today, we deployed some performance optimizations in our API. Please let me know if you still have performance issues related to the redirects.

**Comment by dshumsky** [comment]
It's now much faster now (30s -> 0.6s)
Thank you so much @xellio
