### ISSUE TITLE
Update `myrasec_dns_record` after terraform import

### ISSUE THREAD

**Issue by dshumsky** [Myra-Security-GmbH/terraform-provider-myrasec#22]
Hello,

I would like to import DNS-record and than modify it. Unfortunately it doesn't work as expected. Please find the steps to reproduce:
----------------------------------------------
1)
terraform import myrasec_dns_record.lidl-si "www.some.com:100101" 
works, but "domain_name" attribute is not imported.
 
2) 
terraform plan 
complains 'The argument "domain_name" is required, but no definition was found.'

3) 
if to add "domain_name" manually 
terraform plan 
returns:
resource "myrasec_dns_record" "www-some-com" {
      + domain_name       = "www.some.com" # forces replacement
...

4)
and even "replacement" doesn't work throwing this error:
terraform apply
myrasec_dns_record.lidl-si: Destroying... [id=www.some.com:100101]

│ Error: Error parsing record id
│ 
│ strconv.Atoi: parsing "www.some.com:100101": invalid syntax

----------------------------------------------
My expectation would be to have a way to modify existing DNS entry.

Thanks in advance!

**Comment by xellio** [comment]
I released a fixed version of the terraform provider. This issue should be solved using version **v1.19.0** of the provider.
Please let me know if it works for you.
