### ISSUE TITLE
Update myrasec_dns_record after terraform import (Part 2)

### ISSUE THREAD

**Issue by dshumsky** [Myra-Security-GmbH/terraform-provider-myrasec#23]
As a follow-up of https://github.com/Myra-Security-GmbH/terraform-provider-myrasec/issues/22:

- I upgraded to v0.19.0
- `terraform import myrasec_dns_record.dns  ...` is just importing as 
```
resource "myrasec_dns_record" "dns" {
 id=10099999
}
```
- `terraform plan` doesn't work with an error: 
myrasec_dns_record.lidl-si: Refreshing state... [id=10099999]
╷
│ Error: Error parsing DNS record ID10099999

@xellio Many thanks for taking care...

**Comment by xellio** [comment]
It looks like the domain_name is missing in your state. Your resource definition is missing some required values. Please add 

- domain_name
- record_type
- name
- value
- ttl


Example:

```
resource "myrasec_domain" "xell_io" {
  name = "xell.io"
}

resource "myrasec_dns_record" "www_xell_io" {
  domain_name = "xell.io"
  name = "www.xell.io"
  ttl = 300
  record_type = "CNAME"
  value = "xellio.github.com."
}
```


In my case, when I do

### terraform import

```
➜ terraform import myrasec_domain.xell_io #DOMAINID                                                                                                             
myrasec_domain.xell_io: Importing from ID "#DOMAINID"...
myrasec_domain.xell_io: Import prepared!
  Prepared myrasec_domain for import
myrasec_domain.xell_io: Refreshing state... [id=#DOMAINID]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

```
➜ terraform import myrasec_dns_record.www_xell_io xell.io:#RECORDID                                                                                           
myrasec_dns_record.www_xell_io: Importing from ID "xell.io:#RECORDID"...
myrasec_dns_record.www_xell_io: Import prepared!
  Prepared myrasec_dns_record for import
myrasec_dns_record.www_xell_io: Refreshing state... [id=xell.io:#RECORDID]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

### terraform plan
```
➜ terraform plan
myrasec_domain.xell_io: Refreshing state... [id=#DOMAINID]
myrasec_dns_record.www_xell_io: Refreshing state... [id=#RECORDID]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```
### terraform state show
```
➜  terraform-test terraform state show myrasec_domain.xell_io    
# myrasec_domain.xell_io:
resource "myrasec_domain" "xell_io" {
    auto_update = true
    created     = "SOMETIMESTAMPHERE"
    domain_id   = #DOMAINID
    id          = "#DOMAINID"
    modified    = "SOMETIMESTAMPHERE"
    name        = "xell.io"
    paused      = false

    timeouts {}
}
```

```
➜  terraform-test terraform state show myrasec_dns_record.www_xell_io                                                                                                       
# myrasec_dns_record.www_xell_io:
resource "myrasec_dns_record" "www_xell_io" {
    active            = true
    alternative_cname = "www-xell-io.ax4z.com."
    created           = "SOMETIMESTAMPHERE"
    domain_name       = "xell.io"
    enabled           = true
    id                = "#RECORDID"
    modified          = "SOMETIMESTAMPHERE"
    name              = "www.xell.io"
    port              = 0
    priority          = 0
    record_id         = #RECORDID
    record_type       = "CNAME"
    ttl               = 300
    value             = "xellio.github.com."

    timeouts {}
}
```
If you have still problems, please contact our support team, providing more information about your setup and resource definition(s).

**Comment by dshumsky** [comment]
terraform import myrasec_dns_record.lidl-si "www-new.lidl.si:1006637"
myrasec_dns_record.lidl-si: Importing from ID "www-new.lidl.si:1006637"...
myrasec_dns_record.lidl-si: Import prepared!
  Prepared myrasec_dns_record for import
myrasec_dns_record.lidl-si: Refreshing state... [id=www-new.lidl.si:1006637]

Import successful!

----

terraform state list
myrasec_dns_record.lidl-si

----

terraform state show myrasec_dns_record.lidl-si
# myrasec_dns_record.lidl-si:
resource "myrasec_dns_record" "lidl-si" {
    id = "1006637"

    timeouts {}
}

@xellio this is how it looks on my side

**Comment by xellio** [comment]
Thanks for your response! I will have a further look on this. I will inform you as soon as I have a solution for this problem.

**Comment by xellio** [comment]
@dshumsky - I did some investigation on this and created a new issue ( https://github.com/Myra-Security-GmbH/terraform-provider-myrasec/issues/25 )

**Comment by dshumsky** [comment]
I was using deleted id. With the correct one it's working as expected. 
Thank you, @xellio.
