### ISSUE TITLE
Missing datasource myrasec_ip_filters

### ISSUE THREAD

**Issue by lejardindeden** [Myra-Security-GmbH/terraform-provider-myrasec#26]
Hi,

It seems that the data source for "myrasec_ip_filters" is simply missing. 
Could we please add it ?

Thanks.

**Comment by xellio** [comment]
Hello @lejardindeden 
I released a new version of the provider (v1.20.0). This version should have support for a IP filters datasource.
Please let me know if it works for you as expected.

**Comment by lejardindeden** [comment]
Thanks @xellio,

It is now working as expected.
