### ISSUE TITLE
myrasec_ip_filter import not working anymore

### ISSUE THREAD

**Issue by lejardindeden** [Myra-Security-GmbH/terraform-provider-myrasec#27]
Hi,

I noticed on resource myrasec_ip_filter that the import is not working anymore with v1.20.0 version of Myrasec.
Could you please help fix it.
Thanks in advance.
Julien

**Comment by xellio** [comment]
Hello @lejardindeden 
Can you provide more information? I tried importing an IP filter like this:

```
resource "myrasec_ip_filter" "www_example_com" {
  subdomain_name = "www.example.com"
}
```

```
terraform import myrasec_ip_filter.www_example_com www.example.com:1234

myrasec_ip_filter.www_example_com: Importing from ID "www.example.com:1234"...
myrasec_ip_filter.www_example_com: Import prepared!
  Prepared myrasec_ip_filter for import
myrasec_ip_filter.www_example_com: Refreshing state... [id=www.example.com:1234]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

For me, this works as expected. Please provide information about your resource and how you import the IP filter.
You can send this information - using email/ticketing system - to our support team, too.

Thank you!

**Comment by lejardindeden** [comment]
Hi @xellio,

I currently can not reproduce the issue, so I guess I had some unstable configuration.

Thank you for your support!
Best Regards,
Julien
