### ISSUE TITLE
Allow setting api_base_url via environment

### ISSUE THREAD

**Issue by maltejk** [Myra-Security-GmbH/terraform-provider-myrasec#28]
For testing, it would be great to be able to just set the env, like `MYRASEC_API_BASEURL` to something else

https://github.com/Myra-Security-GmbH/terraform-provider-myrasec/blob/d3284b0f79499ac77103445e93be5f753ee6d3c7/myrasec/provider.go#L34

**Comment by xellio** [comment]
Hello @maltejk 
Can you explain the usecase for this setting? What do you want to do with this "env" setting?

**Comment by maltejk** [comment]
Hello @xellio 

I would like to be able to configure the API URL via environment variables to be able to point to a test endpoint without changing actual code.

This would also be very helpful for https://github.com/maltejk/crossplane-provider-myrasec.

Thank you!

**Comment by maltejk** [comment]
Hi @xellio,

> Right now, Myra does not have a public available testing environment.

I'll talk to our technical contact about that. Maybe a private one exists.

> If you want to point the API URL to a custom/own endpoint, it is possible to do this by defining a variable like this:

While this is certainly a way, I would love to do this in a more direct approach and therefore create this PR.

Would this be an option to add? Thank you for consideration!

**Comment by xellio** [comment]
Hello @maltejk 

Using v1.21.0 it is now possible to set the `api_base_url` using a env variable (`MYRASEC_API_BASE_URL`).
Please let me know if it works for you.

**Comment by maltejk** [comment]
Thank you, looking into it!
