### ISSUE TITLE
myrasec_redirect add comment field

### ISSUE THREAD

**Issue by lejardindeden** [Myra-Security-GmbH/terraform-provider-myrasec#36]
Hi,

Would it be possible to add the comment field in myrasec_redirect ?

Thanks.

**Comment by xellio** [comment]
Hello @lejardindeden 
I will add the field. I will inform you as soon as the comment field is supported and can be used.

**Comment by xellio** [comment]
Hello @lejardindeden 
Now, the new version (v1.25.0) of the provider should support the comment field on redirects.

**Comment by lejardindeden** [comment]
Great!
Thank you @xellio 👍
