### ISSUE TITLE
Support Maintenance pages via Terraform ?

### ISSUE THREAD

**Issue by lejardindeden** [Myra-Security-GmbH/terraform-provider-myrasec#39]
Hi,

Is it plan to support maintenance pages via Myra terraform provider ?
It is a feature we would be interested by.

Thanks in advance for your support.
And thank you for the job done 👍

**Comment by xellio** [comment]
Hello @lejardindeden 

Yes, we plan to support the maintenance pages via Terraform provider in the near future. The base integration in the myrasec-go lib (https://github.com/Myra-Security-GmbH/myrasec-go) is almost done.

**Comment by xellio** [comment]
Hello @lejardindeden
The new version (v1.39.0) now supports maintenance pages. See https://registry.terraform.io/providers/Myra-Security-GmbH/myrasec/latest/docs/resources/maintenance and https://registry.terraform.io/providers/Myra-Security-GmbH/myrasec/latest/docs/data-sources/maintenances for more information/documentation.

**Comment by lejardindeden** [comment]
Great!
Regarding the active flag, I think it make sense to keep it as a read-only field. Indeed start/end should be set instead.

**Comment by xellio** [comment]
Hello @lejardindeden 
Even if this issue is already set to closed state, I want to inform you that using the new version (v1.40.0), the `active` flag on maintenance pages is now supported (RO).
