### ISSUE TITLE
IP Whitelist Request Limiter vs. Whitelist/Blacklist

### ISSUE THREAD

**Issue by owunder** [Myra-Security-GmbH/terraform-provider-myrasec#40]
Currently it's not possible to config ip whitelist limiter with ip ranges. This should be configurable in the same way as whitelist/blacklist.

**Comment by xellio** [comment]
Hello @owunder,
This is correct. Right now, Myra supports only /32 (for IPv4) and /128 (for IPv6) ranges on the "IP Whitelist request limiter".
As soon as Myra supports other networks on this, we will support it in the Terraform provider, too.

**Comment by owunder** [comment]
This isn't practicable if you have an ip-range of /24

**Comment by xellio** [comment]
As Myra does not support /24 on IP whitelist request limiter, you could create your resources for a /24 like this:
```
resource "myrasec_ip_filter" "ip_whitelist_request_limiter" {
    count = 255
    subdomain_name = "www.example.com."
    type = "WHITELIST_REQUEST_LIMITER"
    value = "127.0.0.${count.index}"
    enabled = true
}
```

**Comment by owunder** [comment]
> As Myra does not support /24 on IP whitelist request limiter (right now), you could create your resources for a /24 like this:
> 
> ```
> resource "myrasec_ip_filter" "ip_whitelist_request_limiter" {
>     count = 255
>     subdomain_name = "www.example.com."
>     type = "WHITELIST_REQUEST_LIMITER"
>     value = "127.0.0.${count.index}"
>     enabled = true
> }
> ```

Could you add an additional field like "start_with_host"? Using the "local" variable is not clear

locals {
  start_with_host = 16
}

resource "myrasec_ip_filter" "subarea" {
  count          = 16
  subdomain_name = "www.example.com."
  type           = "WHITELIST_REQUEST_LIMITER"
  value          = "127.0.0.${count.index+local.start_with_host}"
}

**Comment by xellio** [comment]
Hello @owunder,
Implementing a solution like this wont be consistent to the rest of the provider. The solution using the local variable should work and this is one reason why Terraform exists (to do stuff/configuration like this - in "code").

Myra is about to add support for /24 networks on "IP Whitelist Request Limiter". As soon as this is supported in the Myra application/API, we will add support for this in the Terraform provider, too.

**Comment by xellio** [comment]
From now on, it is possible to create IP ranges (IPv4 and IPv6) for the `WHITELIST_REQUEST_LIMITER`.
**Note**: IP ranges for IPv6 will work right now only for `WHITELIST_REQUEST_LIMITER`, not for `WHITELIST` nor `BLACKLIST`.

Example:
```
resource "myrasec_ip_filter" "filterv4" {
  subdomain_name = "www.example.com"
  type = "WHITELIST_REQUEST_LIMITER"
  value = "127.0.0.0/16"
  enabled = true
}

resource "myrasec_ip_filter" "filterv6" {
  subdomain_name = "www.example.com"
  type = "WHITELIST_REQUEST_LIMITER"
  value = "dead:beef::/55"
  enabled = true
}
```
