### ISSUE TITLE
Data source does not provide enough attribute references

### ISSUE THREAD

**Issue by owunder** [Myra-Security-GmbH/terraform-provider-myrasec#46]
Please change the data sources to provide more attribute references.

e. g.: we need the ID for domain example.com in an other workspace. There is no satisfying way to handle this.

This is the current workaround
```
data "myrasec_domains" "domain" {
  filter {
    name = example.com
  }
}

resource "myrasec_ip_filter" "allow_example_ip" {

  subdomain_name = "ALL-${data.myrasec_domains.domain.domains[0].id}"

  type        = "WHITELIST"
  value       = "127.0.0.1/32"
}
```
There is no way to get the subdomain by the data source myrasec_dns_records

This doesn't works
```
data "myrasec_dns_records" "records" {
  filter {
    domain_name = data.myrasec_domains.domain.domains[0].name
    name        = "www"
  }
}
```
Workaround:

```
resource "myrasec_ip_filter" "allow_example_ip" {

  subdomain_name = "www.${data.myrasec_domains.domain.domains[0].name}"

  type        = "WHITELIST"
  value       = "127.0.0.1/32"
}
```

**Comment by xellio** [comment]
Hello @owunder ,
we will check this. I will keep you up to date as soon as we have a solution.

**Comment by xellio** [comment]
Hello @owunder ,

I had a look on this issue but I do not fully understand the problem. I did a test like this:

```
data "myrasec_domains" "domain" {
  filter {
    name = "example.com"
  }
}

data "myrasec_dns_records" "records" {
  filter {
    domain_name = "${data.myrasec_domains.domain.domains[0].name}"
    name = "www"
  }
}

data "myrasec_ip_filters" "ipfilter" {
  filter {
    subdomain_name = data.myrasec_dns_records.records.records[0].name
  }
}
```

This one loads all IP filters for `www.example.com` (in/from the domain `example.com`).

Can you give me more details about this issue? 
You can contact our support team, too, in case you want/have to provide confidential information about your domain setup.
