### ISSUE TITLE
myrasec_domain doesn't support import

### ISSUE THREAD

**Issue by dshumsky** [Myra-Security-GmbH/terraform-provider-myrasec#7]
@xellio Hello Richard!

I'm Dmitry Shumski from mgm-tp.com (working closely with LIDL/SchwarzIT). 
We have plenty of sites managed by Myra (like https://www.lidl.de) and now we want to migrate our infrastructure code from API-based workaround :) to Terraform. 
BTW Thank you so much for actively working now on Terraform.

So, the first thing I came to is the 
_Error: resource myrasec_domain doesn't support import_ 
which doesn't allow import existing configuration. 
Is it going to be implemented? Is there another way to import? Is there a way to chat with you?

Thanks!

**Comment by xellio** [comment]
@dshumsky Hello Dimirty,

Thank you for your feedback!
The import functionality for this provider is my next task and will be implemented asap. I will keep track of the process using this github issue.

Please let me know if you have any problems and/or more feedback on this terraform provider!

Regards,
Richard

**Comment by dshumsky** [comment]
@xellio Thank you! That would be great to get import soon.
One more question I have about "Cache Settings". Is it possible to configure "General domain settings"?

**Comment by xellio** [comment]
Hello @dshumsky 
Yes, it is possible to add a cache setting (or IP filter) on the "General domain settings" by passing the domain ID instead of the subdomain_name.

```hcl
resource "myrasec_cache_setting" "example" {
  subdomain_name = "0000" #replace using your domain ID
  ...
}
```

**Comment by bebehei** [comment]
So, I've built the provider again with dee970c403a0f2a2601992fc1eaf10cd451e09e6

I'm able to spit out the domain ID with the following construct:

```
data "myrasec_domains" "domains_data" {
  filter {
    name = "opsler.de"
  }
}
output "domain_id" {
  value = data.myrasec_domains.domains_data.id
}
```

I'm able to import my previously created domain. But I'm not able to finally run my `terraform apply`:

```
[bebe:~/terraform $ terraform import 'myrasec_domain.domains["opsler.de"]' <ID>
myrasec_domain.domains["opsler.de"]: Importing from ID "<ID>"...
myrasec_domain.domains["opsler.de"]: Import prepared!
  Prepared myrasec_domain for import
myrasec_domain.domains["opsler.de"]: Refreshing state... [id=<ID>]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

[bebe:~/terraform $ terraform apply -refresh=false

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # myrasec_domain.domains["opsler.de"] will be updated in-place
  ~ resource "myrasec_domain" "domains" {
      + auto_update = true
        id          = "<ID>"
      + name        = "opsler.de"
      + paused      = false

        timeouts {}
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

myrasec_domain.domains["opsler.de"]: Modifying... [id=<ID>]

Error: Error updating domain: : This website is already registered at Myra, please contact us if you are the real owner.


  on dns-myrasec.tf line 46, in resource "myrasec_domain" "domains":
  46: resource "myrasec_domain" "domains" {


[bebe:~/terraform] $
```

**Comment by bebehei** [comment]
Oh, well. After running `terraform apply` again, I'm able to have a full configuration:

```
[bebe:~/00todo/b3be-infra/terraform] master* ± terraform apply -refresh=false

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

domain_id = <ID>
```

So, I guess, it somewhat works. May have hit a race condition here. For reference, this is my configuration:

```
resource "myrasec_domain" "domains" {
  for_each = toset(["opsler.de"]) #<- this list is longer, but equivalent for this example
  name = each.value
  auto_update = true
}
```

**Comment by xellio** [comment]
I merged the current, basic import functionality to the master branch. 
Using > v1.17.0 import is supported (basic)
