### ISSUE TITLE
Subdomain -> Settings -> Expert -> Proxy Host Header missing

### ISSUE THREAD

**Issue by dshumsky** [Myra-Security-GmbH/terraform-provider-myrasec#70]
Hello 
It looks like "Subdomain -> Settings -> Expert -> Proxy Host Header" configuration option is missing in "myrasec_settings". 
Could you please add it. 
Thank you, 
Dmitry

**Comment by xellio** [comment]
Hello @dshumsky 

Thank you for your request. We will have a took at this setting and inform you here as soon as this setting (host_header) is supported by the terraform provider

**Comment by smashi** [comment]
Hello @dshumsky,
we created a new version 1.53.0 where this feature is implemented.
