### ISSUE TITLE
myrasec_waf_rule: Fingerprint-condition is not imported

### ISSUE THREAD

**Issue by dshumsky** [Myra-Security-GmbH/terraform-provider-myrasec#71]
There is WAF rule with Fingerprint-condition and CAPTCHA-action.
When I import it by the command:
```
terraform import 'myrasec_waf_rule.NAME' 'DOMAIN:ID'
````
the imported state doesn't have Fingerprint-condition. 

Please fix. Thank you!

**Comment by smashi** [comment]
Hello @dshumsky ,

Thank you for the request, we will have a look on that and will inform you here when the terraform provider supports this.

**Comment by smashi** [comment]
Hello @dshumsky,
we created a new version 1.53.0 where this feature is implemented.
