### ISSUE TITLE
When cache-settings are deleted manually from UI myrasec_cache_setting doesn't recover deletion

### ISSUE THREAD

**Issue by dshumsky** [Myra-Security-GmbH/terraform-provider-myrasec#75]
Steps to reproduce:
- create "myrasec_cache_setting" via Terraform
- delete it from UI
- terraform plan shows Warning. Not proposing to re-create deleted "myrasec_cache_setting"

**Comment by smashi** [comment]
Hello @dshumsky,
Thank you for the request, we will have a look and inform you when the terraform provider supports this.

**Comment by vedranbak** [comment]
Hi @dshumsky, we have released new Terraform Provider version v1.55.0 which includes fix for this issue.

**Comment by smashi** [comment]
fixed in latest version
